"""add_ghost_research_tables

Revision ID: 325e3e58006f
Revises: b466baba4614
Create Date: 2026-02-25 12:44:58.875980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '325e3e58006f'
down_revision: Union[str, Sequence[str], None] = 'b466baba4614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_companies', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_slug', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_role', sa.String(), nullable=True),
    sa.Column('email_tone', sa.String(), nullable=False),
    sa.Column('auto_reply_mode', sa.String(), nullable=False),
    sa.Column('max_auto_replies', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_subject', sa.Text(), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('output_dir', sa.String(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['research_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_campaigns_batch_id', 'research_campaigns', ['batch_id'], unique=False)
    op.create_index('ix_research_campaigns_status', 'research_campaigns', ['status'], unique=False)
    op.add_column('threads', sa.Column('research_campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'threads', 'research_campaigns', ['research_campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'research_campaign_id')
    op.drop_index('ix_research_campaigns_status', table_name='research_campaigns')
    op.drop_index('ix_research_campaigns_batch_id', table_name='research_campaigns')
    op.drop_table('research_campaigns')
    op.drop_table('research_batches')
    # ### end Alembic commands ###
