"""add cc and extra_context to research_campaigns

Revision ID: 37463579f805
Revises: 325e3e58006f
Create Date: 2026-02-27 01:25:44.037730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37463579f805'
down_revision: Union[str, Sequence[str], None] = '325e3e58006f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_campaigns', sa.Column('cc', sa.String(), nullable=True))
    op.add_column('research_campaigns', sa.Column('extra_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_campaigns', 'extra_context')
    op.drop_column('research_campaigns', 'cc')
    # ### end Alembic commands ###
