"""Phase 1 models: threads, emails, contacts, attachments

Revision ID: 99e0b761bc02
Revises: 
Create Date: 2026-02-24 14:49:13.557423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e0b761bc02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('communication_frequency', sa.String(), nullable=True),
    sa.Column('avg_response_time', sa.String(), nullable=True),
    sa.Column('preferred_style', sa.String(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enrichment_source', sa.String(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('auto_reply_mode', sa.String(), nullable=False),
    sa.Column('follow_up_days', sa.Integer(), nullable=False),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('security_score_avg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_gmail_thread_id'), 'threads', ['gmail_thread_id'], unique=True)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bcc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('action_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emails_date', 'emails', ['date'], unique=False)
    op.create_index(op.f('ix_emails_gmail_id'), 'emails', ['gmail_id'], unique=True)
    op.create_index('ix_emails_thread_id', 'emails', ['thread_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('gmail_attachment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_index('ix_emails_thread_id', table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_id'), table_name='emails')
    op.drop_index('ix_emails_date', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_threads_gmail_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
