"""add batch_jobs and batch_items tables

Revision ID: b466baba4614
Revises: bc617d4c65d3
Create Date: 2026-02-24 23:08:48.774434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b466baba4614'
down_revision: Union[str, Sequence[str], None] = 'bc617d4c65d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bcc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_clusters', sa.Integer(), nullable=False),
    sa.Column('clusters_sent', sa.Integer(), nullable=False),
    sa.Column('clusters_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_job_id', sa.Integer(), nullable=False),
    sa.Column('cluster_index', sa.Integer(), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gmail_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_job_id'], ['batch_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_items')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
