"""add unique constraint to thread_outcomes thread_id

Revision ID: bc617d4c65d3
Revises: a8c3cd6c593b
Create Date: 2026-02-24 19:48:36.845256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc617d4c65d3'
down_revision: Union[str, Sequence[str], None] = 'a8c3cd6c593b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_outcomes_thread_id'), table_name='thread_outcomes')
    op.create_index(op.f('ix_thread_outcomes_thread_id'), 'thread_outcomes', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_outcomes_thread_id'), table_name='thread_outcomes')
    op.create_index(op.f('ix_thread_outcomes_thread_id'), 'thread_outcomes', ['thread_id'], unique=False)
    # ### end Alembic commands ###
