"""phase3_4_schema

Revision ID: f5c0bb5a2477
Revises: 99e0b761bc02
Create Date: 2026-02-24 18:43:33.253073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c0bb5a2477'
down_revision: Union[str, Sequence[str], None] = '99e0b761bc02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action_type', 'audit_log', ['action_type'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_timestamp', 'security_events', ['timestamp'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('gmail_draft_id', sa.String(), nullable=True),
    sa.Column('to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bcc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('threads', sa.Column('playbook', sa.String(), nullable=True))
    op.add_column('threads', sa.Column('goal', sa.Text(), nullable=True))
    op.add_column('threads', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('threads', sa.Column('goal_status', sa.String(), nullable=True))
    op.drop_column('threads', 'playbook_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('playbook_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('threads', 'goal_status')
    op.drop_column('threads', 'acceptance_criteria')
    op.drop_column('threads', 'goal')
    op.drop_column('threads', 'playbook')
    op.drop_table('drafts')
    op.drop_table('settings')
    op.drop_index('ix_security_events_timestamp', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_action_type', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
